#!/bin/bash

echo "🧪 Guia de Testes Manuais para SEO do Storybook"
echo "=============================================="
echo ""

echo "📋 URLs para Testar no Navegador:"
echo "================================="
echo ""
echo "🏠 Página Principal:"
echo "   http://localhost:8080"
echo ""
echo "🗺️  Sitemap (para crawlers):"
echo "   http://localhost:8080/sitemap.xml"
echo ""
echo "📄 Componentes Específicos:"
echo "   http://localhost:8080/?path=/docs/components-button--docs"
echo "   http://localhost:8080/?path=/docs/components-inputs-text-input--docs"
echo "   http://localhost:8080/?path=/docs/components-alert--docs"
echo ""

echo "🔍 Testes via DevTools:"
echo "======================="
echo "1. Abra DevTools (F12)"
echo "2. Vá para Console"
echo "3. Execute os comandos:"
echo ""
echo "   // Verificar metadados"
echo "   console.log(document.title);"
echo "   console.log(document.querySelector('meta[name=\"description\"]')?.content);"
echo "   console.log(document.querySelector('meta[property=\"og:title\"]')?.content);"
echo ""

echo "🤖 Simular Crawlers via cURL:"
echo "============================="
echo ""
echo "# Googlebot"
echo "curl -A \"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)\" http://localhost:8080"
echo ""
echo "# Bingbot"
echo "curl -A \"Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)\" http://localhost:8080"
echo ""
echo "# Facebook Crawler"
echo "curl -A \"facebookexternalhit/1.1\" http://localhost:8080"
echo ""

echo "📊 Ferramentas Online de Teste:"
echo "==============================="
echo ""
echo "🔗 Facebook Sharing Debugger:"
echo "   https://developers.facebook.com/tools/debug/"
echo "   Cole: http://localhost:8080"
echo ""
echo "🔗 Twitter Card Validator:"
echo "   https://cards-dev.twitter.com/validator"
echo "   Cole: http://localhost:8080"
echo ""
echo "🔗 Google Rich Results Test:"
echo "   https://search.google.com/test/rich-results"
echo "   Cole: http://localhost:8080"
echo ""
echo "🔗 LinkedIn Post Inspector:"
echo "   https://www.linkedin.com/post-inspector/"
echo "   Cole: http://localhost:8080"
echo ""

echo "📈 Validadores:"
echo "==============="
echo ""
echo "🔗 W3C HTML Validator:"
echo "   https://validator.w3.org/"
echo "   Cole: http://localhost:8080"
echo ""
echo "🔗 XML Sitemap Validator:"
echo "   https://www.xml-sitemaps.com/validate-xml-sitemap.html"
echo "   Cole: http://localhost:8080/sitemap.xml"
echo ""

echo "🚀 Testes de Performance:"
echo "========================="
echo ""
echo "🔗 PageSpeed Insights:"
echo "   https://pagespeed.web.dev/"
echo "   Cole: http://localhost:8080"
echo ""
echo "🔗 GTmetrix:"
echo "   https://gtmetrix.com/"
echo "   Cole: http://localhost:8080"
echo ""

echo "📋 Checklist de Verificação Manual:"
echo "==================================="
echo ""
echo "□ Título da página aparece corretamente"
echo "□ Meta description está presente"
echo "□ Open Graph tags estão configuradas"
echo "□ Sitemap XML é válido e acessível"
echo "□ URLs dos componentes são indexáveis"
echo "□ Conteúdo é visível para crawlers"
echo "□ Tempo de carregamento < 3 segundos"
echo "□ Não há erros de JavaScript bloqueantes"
echo ""

echo "🎯 Para Deploy em Produção:"
echo "==========================="
echo ""
echo "1. Execute: npm run build:storybook"
echo "2. Faça deploy da pasta 'storybook-static'"
echo "3. Configure redirecionamentos para SPAs"
echo "4. Adicione sitemap ao robots.txt:"
echo "   echo 'Sitemap: https://seu-dominio.com/sitemap.xml' > storybook-static/robots.txt"
echo "5. Envie sitemap ao Google Search Console"
echo ""

echo "✅ Implementação SEO está pronta para produção!" 