name: Deploy Ocean Documentation

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'packages/ocean-docs/**'
      - 'packages/ocean-react/**'
      - 'packages/ocean-core/**'
      - '.github/workflows/deploy-docs.yml'
      - 'package.json'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'packages/ocean-docs/**'
      - 'packages/ocean-react/**'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Ocean packages
        run: yarn build:libs

      # Deploy do Storybook primeiro (na raiz)
      - name: Deploy Storybook
        run: yarn deploy:storybook -- --ci --keep-files docs/
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Depois build e deploy do Docusaurus em /docs
      - name: Build documentation
        run: yarn build:docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/ocean-docs/build
          destination_dir: docs
          keep_files: true # Mantém os arquivos do Storybook na raiz

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Ocean packages
        run: yarn build:libs

      - name: Build Storybook
        run: yarn build:storybook

      - name: Build documentation
        run: yarn build:docs

      - name: Test serve documentation
        run: |
          cd packages/ocean-docs
          yarn serve &
          sleep 10
          curl -f http://localhost:3000/ || exit 1

      - name: Test serve Storybook
        run: |
          yarn serve:storybook &
          sleep 10
          curl -f http://localhost:6006/ || exit 1
